spring.application.name=fp_micro_configserver

server.port=8888

# Configuración para repositorio local de archivos (ACTIVO)
#spring.cloud.config.server.git.uri=file:///${user.dir}/../fp_files_configproperties
spring.cloud.config.server.git.uri=file:///C:/Users/bruno.gil.ASPIRESYS/Documents/VSCodeProjects/Final Project/fp_files_configproperties
spring.cloud.config.server.git.search-paths=**

# Configuración para repositorio remoto GitHub (DESHABILITADO)
# Para usar GitHub, descomenta las siguientes líneas y comenta la configuración local
#spring.cloud.config.server.git.uri=https://github.com/BrunoGil-AS/fp_files_configproperties.git
#spring.cloud.config.server.git.username=BrunoGil-AS
#spring.cloud.config.server.git.password=***REMOVED***
#spring.cloud.config.server.git.search-paths=**


app.allowed.origins=http://localhost:8080,http://localhost:8081,http://localhost:9001,http://localhost:9002,http://localhost:9003

# Configuración de seguridad
app.security.localhost.ipv4=127.0.0.1
app.security.localhost.ipv6=0:0:0:0:0:0:0:1
app.security.error.message=Only local requests are allowed

# Configuración para servir archivos estáticos (logback-spring.xml)
spring.cloud.config.server.native.searchLocations=file:///C:/Users/bruno.gil.ASPIRESYS/Documents/VSCodeProjects/Final Project/fp_files_configproperties